apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: rating service review
spec:
    trigger:
        type: http
    steps:
        - id: rating-dest
          uses: transformation/rating-service@latest
        - id: rating-dest
          uses: transformation/rating-dest@latest
    variables:
        - name: 6d2727eb-63a0-4eb3-a3d5-35ebcadc5d22
          ref: 6d2727eb-63a0-4eb3-a3d5-35ebcadc5d22
