apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: test=extractor-alert
spec:
    trigger:
        type: http
    steps:
        - id: hello-test
          uses: transformation/test-src-tttt1234@latest
        - id: hello-test
          uses: transformation/hello-test@latest
