apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: pl-create-app-js
spec:
    trigger:
        type: http
    steps:
        - id: cidaas-create-app-js-591470dc
          uses: transformation/src-create-app-js@latest
        - id: cidaas-create-app-js-591470dc
          uses: transformation/cidaas-create-app-js-591470dc@1.0.1
