apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test logs of script
spec:
    type: transformation
    language: javascript
    config:
        binddn: cn=admin,dc=example,dc=org
        binddnpw: N2t7rrNiQVM0VjRUqlMB
        groupBaseDN: ou=Sync2Cidaas,ou=Sicherheit,ou=Gruppen,ou=_Creditplus,dc=example,dc=org
        ldapurl: ldap://172.26.2.225:1389
        userActiveAttributeKey: userAccountControl
        userBaseDN: ou=users,dc=example,dc=org
        userObjectClassFilter: person
    signatureVersion: v1
