apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: ashking
spec:
    trigger:
        type: http
    steps:
        - id: t-g-dest-js-templ
          uses: transformation/t-g-sc-13@latest
        - id: t-g-dest-js-templ
          uses: transformation/t-g-tr@latest
        - id: t-g-dest-js-templ
          uses: transformation/t-g-dest-js-templ@latest
