apiVersion: cnips.io/v1
kind: Component
metadata:
    name: getAllProjectIds
spec:
    type: transformation
    language: golang
    config:
        cmiBaseURL: https://cmi-dev.cidaas.com/management-srv/v5/admin/release/basemicroservices
        cmiToken: '[REDACTED]'
        limit: "10"
        skip: "0"
    signatureVersion: v2
