apiVersion: cnips.io/v1
kind: Component
metadata:
    name: ashsource1
spec:
    type: source
    sourceType: STANDARD
    description: ash tests sources
    apiAccessRef: 9c97b608-081a-45e2-93ea-95abe7e3d4eb
