apiVersion: cnips.io/v1
kind: Function
metadata:
    name: t-g-ui-sc-2
spec:
    runtime: js
    description: 'aswasfdas '
    config:
        sad: asd
    apiAccessRef: 41695003-353a-4c01-83d0-7231a817e713
    signatureVersion: v3
    templateVersion: V3
