apiVersion: cnips.io/v1
kind: Component
metadata:
    name: FD_CREATE_COMPANY_XFORM
spec:
    type: transformation
    language: javascript
    config:
        api_key: '[REDACTED]'
        freshdesk_url: https://widastechnologiesgmbh-help.freshdesk.com
    signatureVersion: v1
