apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: FD to Gitlab
spec:
    trigger:
        type: http
    steps:
        - id: gitlab-ticket
          uses: transformation/freshdesk@latest
        - id: gitlab-ticket
          uses: transformation/get-fd-ticket@1.0.0
        - id: gitlab-ticket
          uses: transformation/gitlab-ticket@1.0.0
