apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: aishwarya 12345678
spec:
    trigger:
        type: http
    steps:
        - id: template-dest
          uses: transformation/t-g-sc-13@latest
        - id: template-dest
          uses: transformation/ash-tests-things@latest
        - id: template-dest
          uses: transformation/template-dest@latest
