apiVersion: cnips.io/v1
kind: Component
metadata:
    name: javascript-f4a40a94-e909-4576-865f-f4b1c36e7f62
spec:
    type: source
    sourceType: STANDARD
    apiAccessRef: f1ab7941-55b5-4984-9a9b-7a9fd4c837da
