apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: demo-2
spec:
    trigger:
        type: http
    steps:
        - id: test-demo-2
          uses: transformation/test-demo-2@latest
        - id: test-demo-2
          uses: transformation/tx-demo-2@latest
        - id: test-demo-2
          uses: transformation/test-demo-2@latest
