apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: test-native
spec:
    trigger:
        type: http
    steps:
        - id: d1
          uses: transformation/s1@latest
        - id: d1
          uses: transformation/www@latest
          with:
            expression: items.filter(item, item.price > 100)
        - id: d1
          uses: transformation/www@latest
          with:
            api_access_ref: 03ef16f5-6b1e-4b3b-a306-81d422802dc5
            headers:
                asd: qwe
            method: GET
            payload: '{"name":"raja"}'
            query_params:
                asd: def
            timeout: 10s
            url: https://jsonplaceholder.typicode.com/posts/1
        - id: d1
          uses: transformation/d1@latest
