apiVersion: cnips.io/v1
kind: Function
metadata:
    name: Get-FAASP_1
spec:
    runtime: js
    config:
        Hi: Hello
    apiAccessRef: d716c681-9793-4091-b2b8-dfc97c831812
    signatureVersion: v3
    templateVersion: V3
