apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test-appr-yannick
spec:
    type: approval
    language: golang
    description: testing approval
    config:
        email_from: innacy.raja@widas.in
        sendgrid_api_key: '[REDACTED]'
    signatureVersion: v2
