apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test-demo1
spec:
    type: source
    sourceType: STANDARD
    description: This is http source which takes data from cmi webhook
    apiAccessRef: 8c688170-7880-4d8f-82fe-7249e4cec6df
