apiVersion: cnips.io/v1
kind: Component
metadata:
    name: error-processing-dest
spec:
    type: destination
    language: javascript
    description: Capturing error and processed here
    signatureVersion: v3
