apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: nested-loop-pipeline
spec:
    trigger:
        type: http
    steps:
        - id: check-dest1234
          uses: transformation/src-loop-test@latest
        - id: check-dest1234
          uses: transformation/check-dest1234@latest
