apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: test-001
spec:
    trigger:
        type: http
    steps:
        - id: faas-sl
          uses: transformation/go-src-001@latest
        - id: faas-sl
          uses: transformation/go-mark-processed@1.0.0
        - id: faas-sl
          uses: transformation/faas-sl@1.0.0
