apiVersion: cnips.io/v1
kind: Function
metadata:
    name: t-g-secure-test (Copy)
spec:
    runtime: js
    apiAccessRef: 8c688170-7880-4d8f-82fe-7249e4cec6df
    signatureVersion: v1
    templateVersion: V1
