apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: batches-sent test
spec:
    trigger:
        type: http
    steps:
        - id: test-new-js
          uses: transformation/replicate-batches-issue@latest
        - id: test-new-js
          uses: transformation/test-new-js@1.0.0
