apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: update table
spec:
    trigger:
        type: http
    steps:
        - id: d1
          uses: transformation/s2@latest
        - id: d1
          uses: transformation/table-for-config@latest
        - id: d1
          uses: transformation/d1@latest
