apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Office-enrich-token-xform
spec:
    type: transformation
    language: javascript
    config:
        client_id: c2bddbe3-5413-4979-b86a-a4614469333c
        client_secret: '[REDACTED]'
        office_url: https://login.microsoftonline.com/
        tenant_id: c4b3e4a3-9f83-4349-b2e3-a46936cfd3e1
    signatureVersion: v1
