apiVersion: cnips.io/v1
kind: Component
metadata:
    name: "300620251"
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    description: "30062025"
    config:
        "1": ENC[AESGCM:v1:9e1c985e0c6beba2c9ae9eb0fab2d2dc58bf4467a76ed0de7119572f7b]
    apiAccessRef: 25d93fd2-2b92-4d73-82ac-8be6bab8bd49
    signatureVersion: v1
