apiVersion: cnips.io/v1
kind: Component
metadata:
    name: FD_VALIDATE_GROUPINFO_DB
spec:
    type: decision
    language: javascript
    config:
        customerGroupType: cidaas-customer-grouptype
        customerGroupType1: Customers
    signatureVersion: v1
