apiVersion: cnips.io/v1
kind: Component
metadata:
    name: freshdesk_create_contact_agent_xform
spec:
    type: transformation
    language: javascript
    config:
        api_key: ENC[AESGCM:v1:102ad6b5a7006d0701ea6e88f26d2baf7e3badc73cc02f830affd1c74b17a68aa40535a8f84aa745dc7134c9fd880b]
        base_url: https://qa.cidaas.de
        company_id: "204000052118"
        contactRoles: TECHNICAL_ADMIN,TICKET_REPORTER
        customerGroupType: Customers
        freshdesk_url: https://widastechnologiesgmbh-help.freshdesk.com
        groupId: freshdesk
    signatureVersion: v1
