apiVersion: cnips.io/v1
kind: Component
metadata:
    name: getProjectIdsFromServiceNames
spec:
    type: transformation
    language: golang
    config:
        gitlabBaseURL: '[REDACTED]'
        gitlabToken: '[REDACTED]'
        group: ""
    signatureVersion: v2
