apiVersion: cnips.io/v1
kind: Function
metadata:
    name: aishwryas-change-log-test
spec:
    runtime: js
    config:
        dsdde: edfefef
        test: aish
    signatureVersion: v3
    templateVersion: V3
