apiVersion: cnips.io/v1
kind: Function
metadata:
    name: t-g-err-go
spec:
    runtime: go
    config:
        asd: asd
        asfasf: asfasf
        dasdas: ads
        er: wre
        sdf: sdf
        te: ets
        we: sdf
        werwer: sxdfvsdf
        zxczx: zxczxcs
    apiAccessRef: a1696cec-9491-480b-85d1-c4c5c2b80779
    signatureVersion: v2
    templateVersion: V2
