apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: g-t-versioning
spec:
    trigger:
        type: http
    steps:
        - id: test-go-retry-pipeline-2
          uses: transformation/js-extractor-001@latest
        - id: test-go-retry-pipeline-2
          uses: transformation/bkg-bd-tt-9@1.0.1
        - id: test-go-retry-pipeline-2
          uses: native/decision@1
        - id: test-go-retry-pipeline-2
          uses: transformation/test-go-retry-pipeline@1.0.1
        - id: test-go-retry-pipeline-2
          uses: transformation/test-go-retry-pipeline@1.0.0
