apiVersion: cnips.io/v1
kind: Function
metadata:
    name: express-001
spec:
    runtime: js
    config:
        client_id: "1234567"
    apiAccessRef: 1d196690-7d0b-4533-ae31-dcf61e19d42e
    signatureVersion: v2
    templateVersion: V2
