apiVersion: cnips.io/v1
kind: Component
metadata:
    name: New Update User Go
spec:
    type: destination
    language: golang
    config:
        base_url: https://widas-test.cidaas.eu
        client_id: 08cd5b90-ee84-4783-a692-6bf3aac025a3
        client_secret: '[REDACTED]'
    signatureVersion: v2
