apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: test token app
spec:
    trigger:
        type: http
    steps:
        - id: d1
          uses: transformation/s2@latest
        - id: d1
          uses: transformation/token-gen@latest
        - id: d1
          uses: transformation/d1@latest
