apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Cidaas - Update Group Go-f8680d43-0fce-4874-982f-82c162c64ee3
spec:
    trigger:
        type: http
    steps:
        - id: golang-c3359f3d-7fd6-41b8-a2a8-9f7c83f8fc32
          uses: transformation/golang-8a4354d6-306f-4399-bf31-816131f050bf@latest
        - id: golang-c3359f3d-7fd6-41b8-a2a8-9f7c83f8fc32
          uses: transformation/golang-c3359f3d-7fd6-41b8-a2a8-9f7c83f8fc32@latest
