apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Automation DecisionsBlocks uuu
spec:
    type: decision
    language: golang
    description: Description DecisionsBlocks
    config:
        cnips: Automation
    signatureVersion: v2
