apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: ash II
spec:
    trigger:
        type: http
    steps:
        - id: test-ext-dest
          uses: transformation/plain-source@latest
        - id: test-ext-dest
          uses: transformation/throw-error-tx@1.0.1
        - id: test-ext-dest
          uses: transformation/test-ext-dest@1.0.0
