apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test-source-creation2
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    apiAccessRef: 8dc47c84-bf38-49a9-95e0-46d1dec563a2
    signatureVersion: v2
