apiVersion: cnips.io/v1
kind: Component
metadata:
    name: g-t-ext-act2
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    config:
        t: t
    apiAccessRef: 9c97b608-081a-45e2-93ea-95abe7e3d4eb
    signatureVersion: v1
