apiVersion: cnips.io/v1
kind: Component
metadata:
    name: golang-c7147682-246e-4747-89c5-8f5088a8b33a
spec:
    type: destination
    language: golang
    config:
        base_url: https://widas-test.cidaas.eu
        client_id: af2291a6-25d7-4b07-8230-f0803f6c1189
        client_secret: '[REDACTED]'
    signatureVersion: v1
