apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: aishwarya new 12
spec:
    trigger:
        type: http
    steps:
        - id: rating-dest
          uses: transformation/source-12082025@latest
        - id: rating-dest
          uses: transformation/transformation-12082025@latest
          with:
            "1": "1"
            "22": "22"
        - id: rating-dest
          uses: transformation/rating-dest@latest
    variables:
        - name: de456c21-b66f-4884-89d0-eb5191fea3bb
          ref: de456c21-b66f-4884-89d0-eb5191fea3bb
