apiVersion: cnips.io/v1
kind: Function
metadata:
    name: ea
spec:
    runtime: js
    config:
        ess: rews
    apiAccessRef: cd707a64-2eb2-4f47-a0fb-0eef22906ef0
    signatureVersion: v3
    templateVersion: V3
