apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: test-cr-pl
spec:
    trigger:
        type: http
    steps:
        - id: javascript-cd045fa8-827b-41d7-b380-f1d911e91a48
          uses: transformation/javascript-49af7fe7-91bb-4895-9234-427b361f2794@latest
        - id: javascript-cd045fa8-827b-41d7-b380-f1d911e91a48
          uses: transformation/javascript-cd045fa8-827b-41d7-b380-f1d911e91a48@latest
