apiVersion: cnips.io/v1
kind: Component
metadata:
    name: t-g-new-ui
spec:
    type: source
    sourceType: STANDARD
    description: This is a description for the function. I'm testing overflow for longer description. loreum iposium loreum iposiumloreum iposiumloreum iposiumloreum iposiumloreum iposiumloreum iposiumloreum iposium
    config:
        "2": 2asda
        asd: asdasd
        asdasd: asd
    apiAccessRef: fa33be94-7ce8-437e-93b5-c15969dc031c
