apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: ash 30syb ieue fvv
spec:
    trigger:
        type: http
    steps:
        - id: deet1-err-processing-1cdfb1d3
          uses: transformation/test1111@1.0.0
        - id: deet1-err-processing-1cdfb1d3
          uses: transformation/t-g-ui-1@1.0.0
          with:
            'asd ': ' asfa '
            'asf ': asf af
            'awsd ': 'asda '
        - id: deet1-err-processing-1cdfb1d3
          uses: transformation/deet1-err-processing-1cdfb1d3@1.0.0
