apiVersion: cnips.io/v1
kind: Function
metadata:
    name: Function - PUT - 13082025
spec:
    runtime: js
    description: Function - PUT - 13082025
    config:
        "1": "1"
    apiAccessRef: 81c76369-5da3-440d-9115-62646f22c5d5
    signatureVersion: v3
    templateVersion: V3
