apiVersion: cnips.io/v1
kind: Component
metadata:
    name: '[cspace]Hubspot_LinkCompanyContact'
spec:
    type: transformation
    language: golang
    description: Link contact to company based on contactId and companyId
    config:
        hubspotBaseURL: '[REDACTED]'
        hubspotToken: '[REDACTED]'
    signatureVersion: v2
