apiVersion: cnips.io/v1
kind: Component
metadata:
    name: '[WidasEnt]Get cidaas user info'
spec:
    type: transformation
    language: golang
    description: Loading cidaas user info based on given sub
    config:
        cidaasBaseURL: https://accounts.cidaas.com
    signatureVersion: v2
