apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Switch-19112025-Python
spec:
    type: switch
    language: javascript
    description: Switch-19112025-Python
    config:
        key: '[REDACTED]'
    signatureVersion: v1
