apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Cidaas - Create User Go-f75f53b1-0ef9-47fa-9cf2-15673adf8ba9
spec:
    trigger:
        type: http
    steps:
        - id: golang-c3d74c48-6225-41d3-b064-a5650e9c96bc
          uses: transformation/golang-388b4703-3858-459d-bd0e-48af3b564d56@latest
        - id: golang-c3d74c48-6225-41d3-b064-a5650e9c96bc
          uses: transformation/golang-c3d74c48-6225-41d3-b064-a5650e9c96bc@latest
