apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Test - Gibcen
spec:
    trigger:
        type: http
    steps:
        - id: js-dest-001
          uses: transformation/js-src-001@latest
        - id: js-dest-001
          uses: transformation/go-uppercase@1.0.0
        - id: js-dest-001
          uses: transformation/js-dest-001@1.0.0
