apiVersion: cnips.io/v1
kind: Component
metadata:
    name: bkg-build-success
spec:
    type: decision
    language: golang
    description: test
    config:
        test: test
        testabc: test
    signatureVersion: v1
