apiVersion: cnips.io/v1
kind: Component
metadata:
    name: '[WidasEnt]ClientID_QA_Check'
spec:
    type: decision
    language: golang
    config:
        client_Id: d72e1fb2-c4b3-4e65-9b6d-b57fbcd90418
    signatureVersion: v2
