apiVersion: cnips.io/v1
kind: Component
metadata:
    name: token-gen
spec:
    type: transformation
    language: golang
    description: token generator
    config:
        cidaas_base_url: ' https://qa.cidaas.de/'
        client_id: 46f3ae1a-a495-47b6-ae2b-0492b9883fc0
        client_secret: '[REDACTED]'
        table_base_url: https://dev.cnips.eu
        tableApiKey: '[REDACTED]'
        tableId: 1a4c1ec4-0638-49a0-bb65-9c2f939d6145
        workspace: default
    signatureVersion: v2
