apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test table (Copy)
spec:
    type: transformation
    language: golang
    description: testing table
    config:
        apiKey: '[REDACTED]'
        table_base_url: https://dev.cnips.eu
        tableId: 91c20eb3-86e8-40ff-a8c4-b8e48792b419
        workspace: default
    signatureVersion: v2
