apiVersion: cnips.io/v1
kind: Component
metadata:
    name: t-g-tr-py-templ (Copy)
spec:
    type: transformation
    language: python
    description: asdfsdf asda af a afasfawrrqwer ewre
    config:
        s: s
    signatureVersion: v1
