apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: multiple-destinations
spec:
    trigger:
        type: http
    steps:
        - id: ash-all-js
          uses: transformation/mytest@latest
        - id: ash-all-js
          uses: native/decision@1
        - id: ash-all-js
          uses: native/decision@1
        - id: ash-all-js
          uses: transformation/test-a013044a@1.0.0
        - id: ash-all-js
          uses: transformation/ash-all-js@1.0.0
