apiVersion: cnips.io/v1
kind: Component
metadata:
    name: mydestforconfig
spec:
    type: destination
    language: javascript
    config:
        a: "1"
        b: "2"
        c: "3"
    signatureVersion: v3
