apiVersion: cnips.io/v1
kind: Function
metadata:
    name: test-ash
spec:
    runtime: go
    description: ytfyfyugiu
    apiAccessRef: 8265b5cd-d58d-40b8-9280-f9f5504849bf
    signatureVersion: v1
    templateVersion: V1
