apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: check transformationMap
spec:
    trigger:
        type: http
    steps:
        - id: ash-all-js
          uses: transformation/ash-all-js@latest
