apiVersion: cnips.io/v1
kind: Component
metadata:
    name: ash tests things
spec:
    type: transformation
    language: javascript
    config:
        aish: warya
        rest: nope
    signatureVersion: v1
