apiVersion: cnips.io/v1
kind: Component
metadata:
    name: FD_DEST_UPDATEUSERCUSTOMFIELD
spec:
    type: destination
    language: javascript
    config:
        base_url: https://widas-test.cidaas.eu
    signatureVersion: v1
