apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test-extract
spec:
    type: source
    sourceType: EXTRACTOR
    language: golang
    config:
        gitlabBaseUrl: '[REDACTED]'
        gitlabToken: '[REDACTED]'
        packets: "100"
        reportDurationDays: "7"
        reportGroupId: "4413"
    apiAccessRef: 03ef16f5-6b1e-4b3b-a306-81d422802dc5
    signatureVersion: v2
