apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: TOKEN-PL
spec:
    trigger:
        type: http
    steps:
        - id: fd-dest
          uses: transformation/freshdesk-with-code-src@latest
        - id: fd-dest
          uses: transformation/fd-get-token-xform@1.0.0
        - id: fd-dest
          uses: transformation/fd-dest@1.0.0
