apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Cidaas - Create Group JS-7afe0e33-1915-41d3-a900-978267277609
spec:
    trigger:
        type: http
    steps:
        - id: javascript-c3233ea4-d053-4416-9ec4-ec7a172051b6
          uses: transformation/javascript-d180a96c-2b15-43f9-885f-a9238dfc599e@latest
        - id: javascript-c3233ea4-d053-4416-9ec4-ec7a172051b6
          uses: transformation/javascript-c3233ea4-d053-4416-9ec4-ec7a172051b6@latest
