apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: c
spec:
    trigger:
        type: http
    steps:
        - id: test-create-version-go
          uses: transformation/dummy@latest
        - id: test-create-version-go
          uses: transformation/test-create-version-go@1.0.0
