apiVersion: cnips.io/v1
kind: Component
metadata:
    name: t-g-ui-ide
spec:
    type: decision
    language: javascript
    description: asda;lsknasd lkna klna w
    config:
        "22": "212"
    signatureVersion: v1
