apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: freshdesk_with_code_pl
spec:
    trigger:
        type: http
    steps:
        - id: fd-dest-2
          uses: transformation/freshdesk-with-code-src@latest
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: transformation/fd-getuserinternal@1.0.0
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: transformation/freshdesk-create-contact-agent-xform@1.0.0
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: transformation/freshdesk-update-contact-agent-xform@1.0.0
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: transformation/freshdesk-delete-contact-agent-xform@1.0.0
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: transformation/freshdesk-create-contact-agent-xform@1.0.0
        - id: fd-dest-2
          uses: transformation/freshdesk-update-contact-agent-xform@1.0.0
        - id: fd-dest-2
          uses: native/decision@1
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest-invalid-user@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest-role-not-exist@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
        - id: fd-dest-2
          uses: transformation/fd-dest@1.0.0
