apiVersion: cnips.io/v1
kind: Component
metadata:
    name: t-g-sc-2
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    description: asdasd
    apiAccessRef: cd707a64-2eb2-4f47-a0fb-0eef22906ef0
    signatureVersion: v2
