apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Cidaas - Create User JS-fcaf7234-b68d-4c1d-ae9b-a748d5c3dfde
spec:
    trigger:
        type: http
    steps:
        - id: javascript-44428d19-48bc-448c-a96b-10a58a4bfa3e
          uses: transformation/javascript-29b094d6-dbde-4999-a883-2c4190794b0a@latest
        - id: javascript-44428d19-48bc-448c-a96b-10a58a4bfa3e
          uses: transformation/javascript-44428d19-48bc-448c-a96b-10a58a4bfa3e@latest
