apiVersion: cnips.io/v1
kind: Function
metadata:
    name: Test-version
spec:
    runtime: go
    description: desc
    apiAccessRef: 03ef16f5-6b1e-4b3b-a306-81d422802dc5
    signatureVersion: v2
    templateVersion: V2
