apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 5d4fe341-e0d2-4b62-9e5f-9652a07ccfdf
    name: 0W45pz4p
    description: Description Configurations
spec:
    type: APIAccess
    ref: 5d4fe341-e0d2-4b62-9e5f-9652a07ccfdf
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
