apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 25d93fd2-2b92-4d73-82ac-8be6bab8bd49
    name: "30062025"
    description: "30062025"
spec:
    type: APIAccess
    ref: 25d93fd2-2b92-4d73-82ac-8be6bab8bd49
    workspaceId: default
    apiAccess:
        apiAccessType: CIDAAS_OAUTH2
        oAuthDetails:
            client_id: "1312"
            client_secret: '[REDACTED]'
            req_scopes: "12312"
            wellknownUrl: https://ssad.com
