apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: ca6bdf4d-59e6-4fde-b9b4-ebc711e73dbe
    name: 5806852315937720650.owasp.org
    description: Description Configurations
spec:
    type: APIAccess
    ref: ca6bdf4d-59e6-4fde-b9b4-ebc711e73dbe
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
