apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 88ce6fb5-1841-4da4-9360-abddee82ef6c
    name: API Access cidaas OAuth2
    description: This is new configuration created for of configuration type API Access  and Access Type as cidaas OAuth2
spec:
    type: APIAccess
    ref: 88ce6fb5-1841-4da4-9360-abddee82ef6c
    workspaceId: default
    apiAccess:
        apiAccessType: CIDAAS_OAUTH2
        oAuthDetails:
            client_id: 302fbace-9b06-4a2d-a2d8-ba1aa10adc1c
            client_secret: '[REDACTED]'
            req_scopes: openid profile email cidaas:register cidaas:invite
            wellknownUrl: https://automation-test.dev.cidaas.eu/.well-known/openid-configuration
