apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 0f3ebe03-66e8-45ef-98df-970a6805b314
    name: ash101
spec:
    type: APIAccess
    ref: 0f3ebe03-66e8-45ef-98df-970a6805b314
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
