apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 8a0d8c4b-1d78-45ba-9683-b62194a6323a
    name: ashfortest
    description: ash
spec:
    type: APIAccess
    ref: 8a0d8c4b-1d78-45ba-9683-b62194a6323a
    workspaceId: default
    apiAccess:
        apiAccessType: CIDAAS_OAUTH2
        oAuthDetails:
            client_id: e12826d4-09f8-4074-926d-0a34f050e752
            client_secret: ENC[AESGCM:v1:d022c51d9a76978b92a59495cecf1ed34fa10372c790736d21457b7972c483ade81b4733bf91af97baeac5e54a4ffedc16992d56c37f7076cc5d6072c7c0b6c2]
            req_scopes: profile
            wellknownUrl: https://qa.cidaas.de/.well-known/openid-configuration
