apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 2bf2702e-2c03-40b9-880c-e8fe02e7b0ea
    name: ashtests123
    description: describe
spec:
    type: APIAccess
    ref: 2bf2702e-2c03-40b9-880c-e8fe02e7b0ea
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
