apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 0d58a0c4-db14-4823-beb7-4fe62081e1ab
    name: 'Automation Configurations) UNION ALL select NULL -- '
    description: Description Configurations
spec:
    type: APIAccess
    ref: 0d58a0c4-db14-4823-beb7-4fe62081e1ab
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
