apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 13a2d5a3-8fed-4df4-bd97-a1972aed5295
    name: Automation Configurations;sleep 15.0;
    description: Description Configurations
spec:
    type: APIAccess
    ref: 13a2d5a3-8fed-4df4-bd97-a1972aed5295
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
