apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: bad14deb-3044-419d-a0e1-bd2ad3212073
    name: 'Automation Configurations;start-sleep -s 15.0 #'
    description: Description Configurations
spec:
    type: APIAccess
    ref: bad14deb-3044-419d-a0e1-bd2ad3212073
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
