apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: f0df2ebf-3397-46b0-92c2-3a51e73d01c6
    name: cat /etc/passwd
    description: Description Configurations
spec:
    type: APIAccess
    ref: f0df2ebf-3397-46b0-92c2-3a51e73d01c6
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
