apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: eac4260d-c0b0-4565-9859-722d633b9805
    name: CFG-APP-eac4260d-c0b0-4565-9859-722d633b9805
spec:
    type: APIAccess
    ref: eac4260d-c0b0-4565-9859-722d633b9805
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
