apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: a519a2b4-03e6-408d-ba45-c7648d9b335e
    name: CFG-USER-a519a2b4-03e6-408d-ba45-c7648d9b335e
spec:
    type: APIAccess
    ref: a519a2b4-03e6-408d-ba45-c7648d9b335e
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
