apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: f52e1050-c8a6-43ec-a109-0e735e596145
    name: cfg-smoke-test-f52e1050-c8a6-43ec-a109-0e735e596145
spec:
    type: APIKEY
    ref: f52e1050-c8a6-43ec-a109-0e735e596145
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: ENC[AESGCM:v1:92f2f28c577dea21b601903a0b68ebf9363676c52a59e2d2060b5ce06e3360aa87a4e1f8]
            apikey_placeholder: smoke-test
            apikey_placement: query
