apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: fa33be94-7ce8-437e-93b5-c15969dc031c
    name: CFG-APP-fa33be94-7ce8-437e-93b5-c15969dc031c
spec:
    type: APIAccess
    ref: fa33be94-7ce8-437e-93b5-c15969dc031c
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
