apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 3be100b7-ea07-414f-91cf-cba37f0a7f2b
    name: cfg-smoke-test-3be100b7-ea07-414f-91cf-cba37f0a7f2b
spec:
    type: APIKEY
    ref: 3be100b7-ea07-414f-91cf-cba37f0a7f2b
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
