apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: a2207164-14df-4fb3-a0fd-33b6932b57a6
    name: CFG-GROUP-a2207164-14df-4fb3-a0fd-33b6932b57a6
spec:
    type: APIAccess
    ref: a2207164-14df-4fb3-a0fd-33b6932b57a6
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
