apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 77225994-e09a-41a4-9147-476db8ba4b89
    name: CFG-APP-77225994-e09a-41a4-9147-476db8ba4b89
spec:
    type: APIAccess
    ref: 77225994-e09a-41a4-9147-476db8ba4b89
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
