apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 1cf29bfa-301f-40bc-9f71-47167c3a6f8b
    name: CFG-USER-1cf29bfa-301f-40bc-9f71-47167c3a6f8b
spec:
    type: APIAccess
    ref: 1cf29bfa-301f-40bc-9f71-47167c3a6f8b
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
