apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 92eb3b27-c6f1-4d52-82ad-21e9afe44eb1
    name: CFG-USER-92eb3b27-c6f1-4d52-82ad-21e9afe44eb1
spec:
    type: APIAccess
    ref: 92eb3b27-c6f1-4d52-82ad-21e9afe44eb1
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
