apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 1c9c5078-e6e8-4094-86ac-40f59add23d7
    name: CFG-USER-1c9c5078-e6e8-4094-86ac-40f59add23d7
spec:
    type: APIAccess
    ref: 1c9c5078-e6e8-4094-86ac-40f59add23d7
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
