apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: e45a57d6-8d28-477b-aacb-30cd73232d9a
    name: CIDAAS-OAUTH
spec:
    type: APIAccess
    ref: e45a57d6-8d28-477b-aacb-30cd73232d9a
    workspaceId: default
    apiAccess:
        apiAccessType: CIDAAS_OAUTH2
        oAuthDetails:
            client_id: 08cd5b90-ee84-4783-a692-6bf3aac025a3
            client_secret: '[REDACTED]'
            wellknownUrl: https://widas-test.cidaas.eu/.well-known/openid-configuration
