apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: ef81e042-881a-4bc7-9cfd-98a397f875d8
    name: Configuration - TOTP Based
    description: Configuration - TOTP Based
spec:
    type: APIAccess
    ref: ef81e042-881a-4bc7-9cfd-98a397f875d8
    workspaceId: default
    apiAccess:
        apiAccessType: TOTP
        totpDetails:
            totp_placeholder: "123213"
            totp_placement: header
            totpkey: 74ff0ca9f31335de10b6dda17faf630c7f64580f03b2da9ff5307ca0ce7091c0ada7d12874d96bf367850d0188fcc18620a9a64ae4c9df66ffc4e57861370b9e4167ba1f5c348bdae8d3cdadfda413ea
