apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 220b8cd6-99d3-4d81-9184-cdd3d2eb414e
    name: configname
    description: ASAs
spec:
    type: APIAccess
    ref: 220b8cd6-99d3-4d81-9184-cdd3d2eb414e
    workspaceId: default
    apiAccess:
        apiAccessType: CIDAAS_OAUTH2
        oAuthDetails:
            client_id: uykfjkjh
            client_secret: ENC[AESGCM:v1:2926e93b80e7a2bcc0cbc7fb6740a49ab559e4ec8ed0a4e12393ce5c5af5266264dd696ed128]
