apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 3b690c5e-b155-4c45-a360-21832fdf1fb0
    name: '[Cspace]SelfSignOn_Config'
    description: 'Configuration for cspace self sign on '
spec:
    type: APIAccess
    ref: 3b690c5e-b155-4c45-a360-21832fdf1fb0
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
