apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 9c97b608-081a-45e2-93ea-95abe7e3d4eb
    name: form-builder-fn-courier
    description: in-url-token
spec:
    type: APIAccess
    ref: 9c97b608-081a-45e2-93ea-95abe7e3d4eb
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
