apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: b853cf38-7f59-4c3d-b8b2-21711e2119c8
    name: name1
spec:
    type: APIAccess
    ref: b853cf38-7f59-4c3d-b8b2-21711e2119c8
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
