apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 459949b6-78db-4b63-ba08-cc50060e3262
    name: sai
spec:
    type: KeyValue
    key: ABCD
    value: ABCD
    ref: 459949b6-78db-4b63-ba08-cc50060e3262
    workspaceId: default
    apiAccess:
        apiAccessType: ""
