apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 0aaca04a-0bba-424f-8f98-eeeea599d5ea
    name: <scrIpt>alert(1);</scRipt>
    description: Description Configurations
spec:
    type: APIAccess
    ref: 0aaca04a-0bba-424f-8f98-eeeea599d5ea
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
