apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 154acc94-f5a2-4cf4-8214-8e2b8973f702
    name: t-g-apikey-clone
    description: asfsfd
spec:
    type: APIAccess
    ref: 154acc94-f5a2-4cf4-8214-8e2b8973f702
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
