apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 8e794ea0-fca0-433f-8f45-897704786d79
    name: t-g-demo-paresh-apikey
spec:
    type: APIAccess
    ref: 8e794ea0-fca0-433f-8f45-897704786d79
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
