apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 2cb23861-d962-48d2-9403-fe149588a33d
    name: t-g-genouth-clone
    description: asdasd
spec:
    type: APIAccess
    ref: 2cb23861-d962-48d2-9403-fe149588a33d
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: asd
            client_secret: '[REDACTED]'
            wellknownUrl: https://automation-test.dev.cidaas.eu/.well-known/openid-configuration
