apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 8265b5cd-d58d-40b8-9280-f9f5504849bf
    name: t-g-outh (Copy)
    description: asdfasd
spec:
    type: APIAccess
    ref: 8265b5cd-d58d-40b8-9280-f9f5504849bf
    workspaceId: default
    apiAccess:
        apiAccessType: CIDAAS_OAUTH2
        oAuthDetails:
            client_id: ae00e74b-c39d-4f05-b196-3f33941859c2
            client_secret: '[REDACTED]'
            req_scopes: idvalidation:email-notification
            wellknownUrl: https://porsche-test.cidaas.eu/.well-known/openid-configuration
