apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: f6a1c408-8cea-47cd-83eb-a93c00097644
    name: testddapi
    description: api
spec:
    type: APIAccess
    ref: f6a1c408-8cea-47cd-83eb-a93c00097644
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
