apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 7c07c63b-72c2-4259-89c3-10e676b25db6
    name: test
    description: This is for the test
spec:
    type: APIAccess
    ref: 7c07c63b-72c2-4259-89c3-10e676b25db6
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
