apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: cfd77620-65b7-4fd4-86af-a6d3f079ee1c
    name: test1000-f079ee1c
    description: "123"
spec:
    type: APIAccess
    ref: cfd77620-65b7-4fd4-86af-a6d3f079ee1c
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails: '[REDACTED]'
