apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: e81d644f-76d9-4071-a95d-0c19afd44708
    name: testash100
    description: description
spec:
    type: APIAccess
    ref: e81d644f-76d9-4071-a95d-0c19afd44708
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
