apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 9563a343-dec9-4be4-858c-0da96f444b5b
    name: 'webhook automation config '
spec:
    type: APIAccess
    ref: 9563a343-dec9-4be4-858c-0da96f444b5b
    workspaceId: default
    apiAccess:
        apiAccessType: CIDAAS_OAUTH2
        oAuthDetails:
            client_id: 48fd5acc-7f6e-48fd-8b83-ab43d14e411d
            client_secret: '[REDACTED]'
            wellknownUrl: https://kube-nightlybuild-dev.cidaas.de/.well-known/openid-configuration
