apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 0636d67e-6217-4297-8897-227b4025abfd
    name: Webhook Event
spec:
    type: APIAccess
    ref: 0636d67e-6217-4297-8897-227b4025abfd
    workspaceId: default
    apiAccess:
        apiAccessType: APIKEY
        apikeyDetails:
            apikey: '[REDACTED]'
            apikey_placeholder: '[REDACTED]'
            apikey_placement: '[REDACTED]'
