apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 4d15e9db-a9c9-4ee2-8300-fea91ab594dc
    name: |-
        <xsl:variable name="rtobject" select="runtime:getRuntime()"/>
        <xsl:variable name="process" select="runtime:exec($rtobject,'erroneous_command')"/>
        <xsl:variable name="waiting" select="process:waitFor($process)"/>
        <xsl:value-of select="$process"/>
    description: Description Configurations
spec:
    type: APIAccess
    ref: 4d15e9db-a9c9-4ee2-8300-fea91ab594dc
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
