apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 0e8d68ca-4064-49e2-96a9-88d5044c7230
    name: <xsl:value-of select="document('http://dev.cnips.eu:22')"/>
    description: Description Configurations
spec:
    type: APIAccess
    ref: 0e8d68ca-4064-49e2-96a9-88d5044c7230
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
