apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: e996f1de-d198-44d4-bf74-4400376827bc
    name: zj 3051*2920 zj
    description: Description Configurations
spec:
    type: APIAccess
    ref: e996f1de-d198-44d4-bf74-4400376827bc
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
