apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: 09d0f278-5ce0-4043-b4b3-3a184cbb3822
    name: zj<%=4357*8640%>zj
    description: Description Configurations
spec:
    type: APIAccess
    ref: 09d0f278-5ce0-4043-b4b3-3a184cbb3822
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
