apiVersion: cnips.io/v1
kind: Configuration
metadata:
    id: c1314f5a-7c5e-4449-811b-5a953227deb7
    name: zj#set($x=6350*9341)${x}zj
    description: Description Configurations
spec:
    type: APIAccess
    ref: c1314f5a-7c5e-4449-811b-5a953227deb7
    workspaceId: default
    apiAccess:
        apiAccessType: GEN_OAUTH2
        oAuthDetails:
            client_id: app_9f3a2c7b1d84e6
            client_secret: '[REDACTED]'
            req_scopes: Automation Scope
            wellknownUrl: https://dev.cnips.eu/components
