apiVersion: cnips.io/v1
kind: Function
metadata:
    name: quota usage js faas
spec:
    runtime: js
    apiAccessRef: 12654308-7ca2-43b8-8afd-4b9a6815f40b
    signatureVersion: v1
    templateVersion: V1
