apiVersion: cnips.io/v1
kind: Component
metadata:
    name: go-extractor-001
spec:
    type: source
    language: golang
    apiAccessRef: 1d196690-7d0b-4533-ae31-dcf61e19d42e
    signatureVersion: v1
