apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Sample Switch1
spec:
    type: switch
    language: javascript
    description: Sample to show switch blocks1234
    config:
        test: test
