apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Cidaas - Get App JS-a4dd9888-16e6-48b2-a7c5-50e2541d1354
spec:
    trigger:
        type: http
    steps:
        - id: javascript-1f7b3cec-a792-4f91-9854-6e3f1789c0ff
          uses: transformation/javascript-393c3c86-6223-4d6e-bd18-9583c60f5258@latest
        - id: javascript-1f7b3cec-a792-4f91-9854-6e3f1789c0ff
          uses: transformation/javascript-426d0e88-1506-4c44-b99f-171c96c5bd4c@latest
        - id: javascript-1f7b3cec-a792-4f91-9854-6e3f1789c0ff
          uses: transformation/javascript-1f7b3cec-a792-4f91-9854-6e3f1789c0ff@latest
