apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: create-group-js-pl
spec:
    trigger:
        type: http
    steps:
        - id: cidaas-create-group-js-3af67a1e
          uses: transformation/js-cidaas-grp-src@latest
        - id: cidaas-create-group-js-3af67a1e
          uses: transformation/cidaas-create-group-js-3af67a1e@1.0.2
