apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Cidaas - Update Group JS-c8e974f9
spec:
    type: destination
    language: javascript
    config:
        base_url: https://widas-test.cidaas.eu
        client_id: af2291a6-25d7-4b07-8230-f0803f6c1189
        client_secret: '[REDACTED]'
    signatureVersion: v2
