apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: t-g-err
spec:
    trigger:
        type: http
    steps:
        - id: test-go-dest1
          uses: transformation/t-g-er@latest
        - id: test-go-dest1
          uses: transformation/test-go-dest1@latest
