apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: user deleted 2
spec:
    trigger:
        type: http
    steps:
        - id: user-deleted
          uses: transformation/ash-all-js@latest
        - id: user-deleted
          uses: transformation/user-deleted@1.0.0
