apiVersion: cnips.io/v1
kind: Component
metadata:
    name: cnips-get-details-gitlab
spec:
    type: transformation
    language: javascript
    config:
        gitlab_token: '[REDACTED]'
    signatureVersion: v3
