apiVersion: cnips.io/v1
kind: Function
metadata:
    name: test-func-tt
spec:
    runtime: js
    description: This is for the test purpose only
    config:
        apikey: '[REDACTED]'
        secret: '[REDACTED]'
        test: test
    signatureVersion: v3
    templateVersion: V3
