apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Success-webhook-gitlab-ticket-create
spec:
    type: destination
    language: golang
    config:
        gitlabBaseUrl: '[REDACTED]'
        gitlabToken: '[REDACTED]'
    signatureVersion: v2
