apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: mypipeline1
spec:
    trigger:
        type: http
    steps:
        - id: javascript-cd045fa8-827b-41d7-b380-f1d911e91a48
          uses: transformation/source-12082025@latest
        - id: javascript-cd045fa8-827b-41d7-b380-f1d911e91a48
          uses: transformation/ash-tests-things@latest
        - id: javascript-cd045fa8-827b-41d7-b380-f1d911e91a48
          uses: transformation/trans-go-v1@latest
        - id: javascript-cd045fa8-827b-41d7-b380-f1d911e91a48
          uses: native/decision@1
        - id: javascript-cd045fa8-827b-41d7-b380-f1d911e91a48
          uses: transformation/deet1-err-processing-1cdfb1d3@1.0.0
        - id: javascript-cd045fa8-827b-41d7-b380-f1d911e91a48
          uses: transformation/javascript-cd045fa8-827b-41d7-b380-f1d911e91a48@latest
