apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: g-t-version
spec:
    trigger:
        type: http
    retry:
        maxAttempts: 1
        backoffSec: 60
    steps:
        - id: test-go-retry-pipeline
          uses: transformation/g-t-editor@latest
        - id: test-go-retry-pipeline
          uses: transformation/bkg-bd-tt-8@eb6d1c0f-d7c7-4625-9140-5bdc13e10c3a
        - id: test-go-retry-pipeline
          uses: transformation/test-go-retry-pipeline@cbb1459d-d025-4b0f-9eb9-d61d12174567
