apiVersion: cnips.io/v1
kind: Component
metadata:
    name: freshdesk_delete_contact_agent_xform
spec:
    type: transformation
    language: javascript
    config:
        api_key: '[REDACTED]'
        api_key_old: '[REDACTED]'
        company_id: "204000052118"
        freshdesk_url: https://widastechnologiesgmbh-help.freshdesk.com
        groupId: freshdesk
    signatureVersion: v1
