apiVersion: cnips.io/v1
kind: Component
metadata:
    name: '[Cspace]Hubspot_CheckForAlreadyExistingCompany'
spec:
    type: decision
    language: golang
    description: Checks if a "company" field of the event is empty or contains information about an existing hubspot company.
    config:
        hubspotBaseURL: '[REDACTED]'
        hubspotToken: '[REDACTED]'
    signatureVersion: v2
