apiVersion: cnips.io/v1
kind: Component
metadata:
    name: metrics_measurement_js
spec:
    type: destination
    language: javascript
    description: metrics_measurement_js
    signatureVersion: v3
