apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: retry test go pipeline1
spec:
    trigger:
        type: http
    retry:
        maxAttempts: 3
        backoffSec: 60
    steps:
        - id: test-go-retry-pipeline
          uses: transformation/test-source-retry-pipeline@latest
        - id: test-go-retry-pipeline
          uses: transformation/retry-pipeline-simulate-failure@1.0.0
        - id: test-go-retry-pipeline
          uses: transformation/test-go-retry-pipeline@1.0.0
