apiVersion: cnips.io/v1
kind: Component
metadata:
    name: ext-v2-test
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    apiAccessRef: 106d3a05-5bf7-4f28-95f6-1b1af45b9666
    signatureVersion: v2
