apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: version-pl2
spec:
    trigger:
        type: http
    steps:
        - id: just-log
          uses: transformation/src-special-char-rename@latest
        - id: just-log
          uses: transformation/js-run-test@1.0.0
        - id: just-log
          uses: transformation/just-log@1.0.0
