apiVersion: cnips.io/v1
kind: Function
metadata:
    name: email-validation-endpoint
spec:
    runtime: go
    description: Parses a JSON payload to validate the provided email address against a configurable regex pattern and returns validity details.
    config:
        emailpattern: ^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$
    signatureVersion: v2
    templateVersion: V2
