apiVersion: cnips.io/v1
kind: Component
metadata:
    name: ext-from-template (Copy)
spec:
    type: source
    sourceType: EXTRACTOR
    language: golang
    apiAccessRef: 51a66d97-f04d-48d1-b4ee-c2a6164eb929
    signatureVersion: v2
