apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Provisioning to Office
spec:
    trigger:
        type: http
    steps:
        - id: microsoft-365
          uses: transformation/iam-event-trigger@latest
        - id: microsoft-365
          uses: transformation/get-user-data@latest
        - id: microsoft-365
          uses: native/decision@1
        - id: microsoft-365
          uses: transformation/send-data-to-google-workspace@latest
        - id: microsoft-365
          uses: transformation/microsoft-365@latest
    variables:
        - name: b66b0e70-7d43-47f9-b840-4570e554c284
          ref: b66b0e70-7d43-47f9-b840-4570e554c284
