apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Cidaas - Delete App JS-cdc44d47-d2c7-4145-a2c9-d1be5d6cdbe4-1
spec:
    trigger:
        type: http
    steps:
        - id: javascript-4e997dc9-969c-4b84-8318-bf08a964fe10
          uses: transformation/javascript-49af7fe7-91bb-4895-9234-427b361f2794@latest
        - id: javascript-4e997dc9-969c-4b84-8318-bf08a964fe10
          uses: transformation/javascript-4e997dc9-969c-4b84-8318-bf08a964fe10@latest
