apiVersion: cnips.io/v1
kind: Component
metadata:
    name: create, update, terminate
spec:
    type: source
    sourceType: STANDARD
    description: created for manu m
    apiAccessRef: 0eb5f87c-8cd1-4b35-8a4c-7b9b305ef3c2
