apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: pl-err-processing
spec:
    trigger:
        type: http
    steps:
        - id: dest1-err-processing
          uses: transformation/src-err-processing@latest
        - id: dest1-err-processing
          uses: transformation/dest1-err-processing@1.0.0
