apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: pl-errHandling
spec:
    trigger:
        type: http
    steps:
        - id: dest-errhandling1
          uses: transformation/src-errhandling@latest
        - id: dest-errhandling1
          uses: transformation/dest-errhandling1@1.0.0
