apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Test-Office-usr-provisioning-pl
spec:
    trigger:
        type: http
    steps:
        - id: no-action-needed-dest
          uses: transformation/test-office-usr-provisioning-src@latest
        - id: no-action-needed-dest
          uses: native/decision@1
        - id: no-action-needed-dest
          uses: transformation/fd-getuserinternal@1.0.0
        - id: no-action-needed-dest
          uses: transformation/test-office-usr-provisioning-dest@1.0.0
        - id: no-action-needed-dest
          uses: transformation/no-action-needed-dest@1.0.0
