apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: atestsswitches
spec:
    trigger:
        type: http
    steps:
        - id: d3
          uses: transformation/cnips-standard-source@latest
        - id: d3
          uses: native/switch@1
        - id: d3
          uses: transformation/d1@latest
        - id: d3
          uses: transformation/d3@latest
