apiVersion: cnips.io/v1
kind: Component
metadata:
    name: dest-special-char-4
spec:
    type: destination
    language: javascript
    config:
        dummy: d\ data \\
        test: t \ data \\
    signatureVersion: v1
