apiVersion: cnips.io/v1
kind: Component
metadata:
    name: '[Cspace]CreateUserGroupAndAssignUser'
spec:
    type: transformation
    language: golang
    description: From a pre-created payload create the user group and assign user to it
    config:
        cidaasBaseURL: https://qa.cidaas.de
    signatureVersion: v2
