apiVersion: cnips.io/v1
kind: Component
metadata:
    name: sdsdsgf
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    apiAccessRef: bfe8dfc2-0f52-440b-bf47-e8b7973966ee
    signatureVersion: v2
