apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: '[Rebuild] Dev-Environment'
spec:
    trigger:
        type: http
    steps:
        - id: updatefiles
          uses: transformation/getallexistingprojects@latest
        - id: updatefiles
          uses: transformation/getallprojectids@1.0.0
        - id: updatefiles
          uses: transformation/processtaskusingprojectids@1.0.0
        - id: updatefiles
          uses: transformation/updatefiles@1.0.0
