apiVersion: cnips.io/v1
kind: Function
metadata:
    name: t-g-ui-tem-late
spec:
    runtime: js
    description: asasddasd
    config:
        s: s
    apiAccessRef: 41695003-353a-4c01-83d0-7231a817e713
    signatureVersion: v3
    templateVersion: V3
