apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test-approval-1
spec:
    type: approval
    language: javascript
    config:
        email_from: innacy.raja@widas.in
        sendgrid_api_key: '[REDACTED]'
    signatureVersion: v3
