apiVersion: cnips.io/v1
kind: Component
metadata:
    name: t-g-source-ext-js
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    description: asdasd
    apiAccessRef: 983f7ceb-c47d-458f-a899-c656909e1fd9
