apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: test-multi-pl2
spec:
    trigger:
        type: http
    steps:
        - id: test-a013044a
          uses: transformation/src-special-char-rename@latest
        - id: test-a013044a
          uses: native/decision@1
        - id: test-a013044a
          uses: transformation/just-log@1.0.0
        - id: test-a013044a
          uses: transformation/test-a013044a@1.0.0
