apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Cidaas - Create User JS-b9af7864-f6e3-4e16-a735-018d93bd67c2
spec:
    trigger:
        type: http
    steps:
        - id: javascript-6f26e8c8-568c-4886-85bd-35848cf14dcb
          uses: transformation/javascript-024000db-7457-4435-9799-55406966502b@latest
        - id: javascript-6f26e8c8-568c-4886-85bd-35848cf14dcb
          uses: transformation/javascript-6f26e8c8-568c-4886-85bd-35848cf14dcb@latest
