apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: version-pl5
spec:
    trigger:
        type: http
    steps:
        - id: just-log
          uses: transformation/src-special-char-rename@latest
        - id: just-log
          uses: transformation/just-log@latest
