apiVersion: cnips.io/v1
kind: Component
metadata:
    name: destination1
spec:
    type: destination
    language: javascript
    config:
        EMAIL_FROM: ""
        SENDGRID_API_KEY: ""
        TEMPLATE_ID: ""
    signatureVersion: v1
