apiVersion: cnips.io/v1
kind: Component
metadata:
    name: CheckAndCreateEventOverviewTable
spec:
    type: transformation
    language: javascript
    config:
        gitlabBaseUrl: '[REDACTED]'
        gitlabToken: '[REDACTED]'
    signatureVersion: v2
