apiVersion: cnips.io/v1
kind: Component
metadata:
    name: t-g-sc-14
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    description: wfd
    apiAccessRef: 983f7ceb-c47d-458f-a899-c656909e1fd9
    signatureVersion: v2
