apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: js-test-002
spec:
    trigger:
        type: http
    steps:
        - id: js-test-001
          uses: transformation/js-src-001@latest
        - id: js-test-001
          uses: transformation/js-charcount@1.0.0
        - id: js-test-001
          uses: transformation/js-uppercase@1.0.0
        - id: js-test-001
          uses: transformation/d1@1.0.0
        - id: js-test-001
          uses: transformation/js-test-001@1.0.0
