apiVersion: cnips.io/v1
kind: Function
metadata:
    name: test config addition
spec:
    runtime: js
    config:
        test: "100"
        test2: "200"
    apiAccessRef: f6a1c408-8cea-47cd-83eb-a93c00097644
    signatureVersion: v1
    templateVersion: V1
