apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: std-src-pl
spec:
    trigger:
        type: http
    steps:
        - id: js-var-test
          uses: transformation/std-src@latest
        - id: js-var-test
          uses: native/decision@1
        - id: js-var-test
          uses: native/decision@1
        - id: js-var-test
          uses: native/decision@1
        - id: js-var-test
          uses: transformation/js-var-test@latest
