apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test-appr-yannick
spec:
    type: source
    sourceType: STANDARD
    description: testing approval flow by yannick
    apiAccessRef: 03ef16f5-6b1e-4b3b-a306-81d422802dc5
