apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: Test-Multi-Version-pl
spec:
    trigger:
        type: http
    steps:
        - id: test-multi-src-version-dest
          uses: transformation/test-multi-version@latest
        - id: test-multi-src-version-dest
          uses: transformation/test-multi-src-version-dest@1.0.0
