apiVersion: cnips.io/v1
kind: Component
metadata:
    name: aimage1 (Copy)
spec:
    type: transformation
    language: javascript
    description: s
    config:
        s: s
    signatureVersion: v1
