apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Cidaas - Delete User JS-4e69fc09
spec:
    type: destination
    language: javascript
    config:
        base_url: ""
        client_id: ""
        client_secret: '[REDACTED]'
    signatureVersion: v1
