apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: testing-auto-error-processing
spec:
    trigger:
        type: http
    steps:
        - id: test-auto-err-dest
          uses: transformation/test-err-src@latest
        - id: test-auto-err-dest
          uses: transformation/test-auto-err-dest@latest
