apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: test001
spec:
    trigger:
        type: http
    steps:
        - id: webhook-event-processing-log-response-2
          uses: transformation/test-demo-8773a0c2@latest
        - id: webhook-event-processing-log-response-2
          uses: native/decision@1
        - id: webhook-event-processing-log-response-2
          uses: transformation/webhook-event-processing-log-response@1.0.0
        - id: webhook-event-processing-log-response-2
          uses: transformation/webhook-event-processing-log-response@1.0.0
