apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Test-transformation12345
spec:
    type: source
    sourceType: STANDARD
    language: golang
    description: This is for the test
    config:
        test: test
        test_a: test
        test_abc: test
        testq: test
        testw: test
    signatureVersion: v2
