apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: TEST-2-DB-ISSU
spec:
    trigger:
        type: http
    steps:
        - id: quota-exec-time-dest
          uses: transformation/source-quota-exec-time@latest
        - id: quota-exec-time-dest
          uses: transformation/quota-exec-time-dest@1.0.0
