apiVersion: cnips.io/v1
kind: Component
metadata:
    name: destination_1
spec:
    type: destination
    language: javascript
    description: destination_1
    config:
        "1": '[REDACTED]'
    signatureVersion: v1
