apiVersion: cnips.io/v1
kind: Component
metadata:
    name: TEST-XFORM-FROM-APP
spec:
    type: transformation
    language: javascript
    config:
        base_url: ""
        client_id: ""
        client_secret: '[REDACTED]'
    signatureVersion: v1
