apiVersion: cnips.io/v1
kind: Component
metadata:
    name: dest-special-char
spec:
    type: destination
    language: javascript
    config:
        special-str: 'This is a string \\ with double backslashes: \\'
    signatureVersion: v1
