apiVersion: cnips.io/v1
kind: Component
metadata:
    name: agent-dest
spec:
    type: destination
    language: golang
    config:
        GITLAB_BASE_URL: '[REDACTED]'
        GITLAB_BOT_USERNAME: '[REDACTED]'
        GITLAB_PROJECT_ID: '[REDACTED]'
        GITLAB_TOKEN: '[REDACTED]'
    signatureVersion: v2
