apiVersion: cnips.io/v1
kind: Component
metadata:
    name: test1-source
spec:
    type: source
    language: javascript
    apiAccessRef: e45a57d6-8d28-477b-aacb-30cd73232d9a
    signatureVersion: v1
