apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: user-deleted
spec:
    trigger:
        type: http
    steps:
        - id: user-deleted
          uses: transformation/ash-all-js@latest
        - id: user-deleted
          uses: transformation/t-g-diff-js@1.0.0
        - id: user-deleted
          uses: transformation/user-deleted@1.0.0
