apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: testcreateuser
spec:
    trigger:
        type: http
    steps:
        - id: cidaas-create-user-js-736e2e98
          uses: transformation/testsimha@latest
        - id: cidaas-create-user-js-736e2e98
          uses: transformation/cidaas-create-user-js-736e2e98@latest
