apiVersion: cnips.io/v1
kind: Component
metadata:
    name: agent-demo-destination-2
spec:
    type: destination
    language: javascript
    config:
        GITLAB_BASE_URL: '[REDACTED]'
        GITLAB_BOT_USERNAME: '[REDACTED]'
        GITLAB_PROJECT_ID: '[REDACTED]'
        GITLAB_TOKEN: '[REDACTED]'
    signatureVersion: v3
