apiVersion: cnips.io/v1
kind: Component
metadata:
    name: IAM Event Trigger
spec:
    type: source
    sourceType: STANDARD
    description: Retrieve an IAM Event
    config:
        Test: Test
    apiAccessRef: 51a66d97-f04d-48d1-b4ee-c2a6164eb929
