apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: DEMO_PIPELINE
spec:
    trigger:
        type: http
    steps:
        - id: demo-destination
          uses: transformation/demo-source@latest
        - id: demo-destination
          uses: transformation/demo-destination@1.0.0
