apiVersion: cnips.io/v1
kind: Component
metadata:
    name: t-g-tr (Copy) (Copy) (Copy) (Copy)
spec:
    type: transformation
    language: golang
    description: sa
    config:
        d: d
    signatureVersion: v2
