apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: freshdesk-user-provisioning-pl
spec:
    trigger:
        type: http
    steps:
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-user-provisioning-src@latest
        - id: freshdesk-user-provisioning-dest
          uses: transformation/fd-getuserinternal@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-create-contact-agent-xform@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-update-contact-agent-xform@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-delete-contact-agent-xform@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-create-contact-agent-xform@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-update-contact-agent-xform@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: native/decision@1
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-update-contact-agent-xform@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-user-provisioning-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/no-action-needed-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/fd-invalid-event-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/fd-dest-invalid-user@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/no-action-needed-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-user-provisioning-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-user-provisioning-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/no-action-needed-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-user-provisioning-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-user-provisioning-dest@1.0.0
        - id: freshdesk-user-provisioning-dest
          uses: transformation/freshdesk-user-provisioning-dest@1.0.0
