apiVersion: cnips.io/v1
kind: Component
metadata:
    name: aishwarya123456
spec:
    type: transformation
    language: javascript
    config:
        "2": "3"
        test: '[REDACTED]'
    signatureVersion: v3
