apiVersion: cnips.io/v1
kind: Component
metadata:
    name: FD_CREATE_CONTACT_XFORM
spec:
    type: transformation
    language: javascript
    config:
        api_key: '[REDACTED]'
        base_url: https://widas-test.cidaas.eu
        company_id: '[REDACTED]'
        freshdesk_url: https://widastechnologiesgmbh.freshdesk.com
    signatureVersion: v1
