apiVersion: cnips.io/v1
kind: Component
metadata:
    name: FD_CREATE_AGENT_XFORM
spec:
    type: transformation
    language: javascript
    config:
        api_key: '[REDACTED]'
        company_id: '[REDACTED]'
        freshdesk_url: https://widastechnologiesgmbh.freshdesk.com
        groupId: freshdesk
    signatureVersion: v1
