apiVersion: cnips.io/v1
kind: Component
metadata:
    name: Gitlab Ticket Updation
spec:
    type: transformation
    language: golang
    config:
        gitlabBaseUrl: '[REDACTED]'
        gitlabToken: '[REDACTED]'
    signatureVersion: v2
