apiVersion: cnips.io/v1
kind: Function
metadata:
    name: location-weather-fetcher
spec:
    runtime: go
    description: Receives a location payload with latitude and longitude, calls a configurable weather API endpoint, and returns the current weather data.
    config:
        apiurl: https://api.open-meteo.com/v1/forecast
        currentparameters: temperature_2m,apparent_temperature,wind_speed_10m
        defaulttimezone: auto
    apiAccessRef: ce333749-752f-43f5-8136-b5f2d138c2fc
    signatureVersion: v2
    templateVersion: V2
