apiVersion: cnips.io/v1
kind: Function
metadata:
    name: test-cidaas-oauth2
spec:
    runtime: js
    config:
        test: test
        test_b: test
        testc: test123
    apiAccessRef: 88ce6fb5-1841-4da4-9360-abddee82ef6c
    signatureVersion: v3
    templateVersion: V3
