apiVersion: cnips.io/v1
kind: Pipeline
metadata:
    name: tesst-gv-pl
spec:
    trigger:
        type: http
    steps:
        - id: test-dest-gv
          uses: transformation/test-src-gv@latest
        - id: test-dest-gv
          uses: transformation/test-dest-gv@1.0.0
    variables:
        - name: 3abdd49d-3071-409a-9a66-b922a69be59f
          ref: 3abdd49d-3071-409a-9a66-b922a69be59f
