apiVersion: cnips.io/v1
kind: Component
metadata:
    name: js-extractor-001
spec:
    type: source
    sourceType: EXTRACTOR
    language: javascript
    apiAccessRef: 1d196690-7d0b-4533-ae31-dcf61e19d42e
    signatureVersion: v1
